import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import "dotenv/config.js";
import Header from "@/components/Header";
import { headers } from "next/headers";
import ContextProvider from "@/components/ContextProvider";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pump.fun",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Obtain the headers directly
  const headersObj = headers();

  const cookies = headersObj.get("cookie"); // Correct usage: `headersObj.get` retrieves the value.

  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider cookies={cookies}>
          <Providers>
            <Header />
            {children}
          </Providers>
        </ContextProvider>
      </body>
    </html>
  );
}
